name: Java CI - Browser from TestNG

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Step 3: Read browser from testng.xml
      - name: Read browser from testng.xml
        id: get_browser
        run: |
          echo "Reading browser from testng.xml..."
          BROWSER=$(xmllint --xpath "string(//parameter[@name='browser']/@value)" testng.xml)
          echo "Browser detected: $BROWSER"
          echo "browser=$BROWSER" >> $GITHUB_ENV

      # Step 4: Set up ChromeDriver if browser is chrome
      - name: Set up ChromeDriver
        if: ${{ env.browser == 'chrome' }}
        uses: actions/setup-chromedriver@v2
        with:
          chromedriver-version: latest

      # Step 5: Set up EdgeDriver if browser is edge
      - name: Set up EdgeDriver
        if: ${{ env.browser == 'edge' }}
        uses: actions/setup-edgedriver@v1
        with:
          edgedriver-version: latest

      # Step 6: Run Maven tests passing browser
      - name: Run tests on ${{ env.browser }}
        run: mvn -B clean test -Dbrowser=${{ env.browser }} -DsuiteXmlFile=testng.xml
