name: Java CI - TestNG Selenium

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  repository_dispatch:
    types: [run-selenium-tests]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Read parameters from testng.xml
        id: read_params
        shell: pwsh
        run: |
          [xml]$xml = Get-Content testng.xml
          foreach ($param in $xml.suite.parameter) {
            echo "$($param.name)=$($param.value)" >> $env:GITHUB_ENV
          }

      - name: Set up ChromeDriver
        if: ${{ env.browser -eq 'chrome' }}
        uses: browser-actions/setup-chrome@v2
        with:
          chrome-version: ${{ env.browserVersion }}
          install-chromedriver: true

      - name: Set up EdgeDriver
        if: ${{ env.browser -eq 'edge' }}
        uses: microsoft/setup-msedge-driver@v1
        with:
          edge-version: ${{ env.browserVersion }}

      - name: Run Selenium tests
        run: |
          mvn -B clean test \
            -Dbrowser=${{ env.browser }} \
            -Dbrowserstack=${{ env.browserstack }} \
            -DbrowserVersion=${{ env.browserVersion }} \
            -Dos=${{ env.os }} \
            -DosVersion=${{ env.osVersion }} \
            -DsuiteXmlFile=testng.xml
