jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        browser: [chrome, edge]
        os: [windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set up ChromeDriver
        if: matrix.browser == 'chrome'
        uses: actions/setup-chromedriver@v2
        with:
          chromedriver-version: latest

      - name: Set up EdgeDriver
        if: matrix.browser == 'edge'
        uses: actions/setup-edgedriver@v1
        with:
          edgedriver-version: latest

      - name: Run tests on ${{ matrix.browser }}
        run: mvn -B clean test -Dbrowser=${{ matrix.browser }}
