name: Java CI - Browser from TestNG

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    # Hardcode browser versions here
    env:
      CHROME_VERSION: "139"
      EDGE_VERSION: "139"

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Step 3: Read browser name from testng.xml
      - name: Read browser from testng.xml
        id: get_browser
        shell: pwsh
        run: |
          [xml]$xml = Get-Content testng.xml
          $browser = $xml.suite.parameter | Where-Object { $_.name -eq 'browser' } | Select-Object -ExpandProperty value
          Write-Host "Browser detected: $browser"
          echo "browser=$browser" >> $env:GITHUB_ENV

      # Step 4: Set up ChromeDriver if browser is Chrome
      - name: Set up ChromeDriver
        if: ${{ env.browser == 'chrome' }}
        uses: browser-actions/setup-chrome@v2
        with:
          chrome-version: ${{ env.CHROME_VERSION }}
          install-chromedriver: true

      # Step 5: Set up EdgeDriver if browser is Edge
      - name: Set up EdgeDriver
        if: ${{ env.browser == 'edge' }}
        uses: browser-actions/setup-edgedriver@v1
        with:
          edgedriver-version: ${{ env.EDGE_VERSION }}

      # Step 6: Run Maven tests
      - name: Run tests on ${{ env.browser }}
        run: mvn -B clean test -Dbrowser=${{ env.browser }} -DsuiteXmlFile=testng.xml
