name: Java CI - TestNG Selenium

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Read parameters from testng.xml
        id: read_params
        shell: pwsh
        run: |
          [xml]$xml = Get-Content testng.xml

          # Read parameters
          $browser = ($xml.suite.parameter | Where-Object { $_.name -eq 'browser' }).value
          $browserVersion = ($xml.suite.parameter | Where-Object { $_.name -eq 'browserVersion' }).value
          $os = ($xml.suite.parameter | Where-Object { $_.name -eq 'os' }).value
          $osVersion = ($xml.suite.parameter | Where-Object { $_.name -eq 'osVersion' }).value
          $browserstack = ($xml.suite.parameter | Where-Object { $_.name -eq 'browserstack' }).value

          Write-Host "Browser: $browser"
          Write-Host "Browser Version: $browserVersion"
          Write-Host "OS: $os"
          Write-Host "OS Version: $osVersion"
          Write-Host "BrowserStack: $browserstack"

          echo "browser=$browser" >> $env:GITHUB_ENV
          echo "browserVersion=$browserVersion" >> $env:GITHUB_ENV
          echo "os=$os" >> $env:GITHUB_ENV
          echo "osVersion=$osVersion" >> $env:GITHUB_ENV
          echo "browserstack=$browserstack" >> $env:GITHUB_ENV

      - name: Set up ChromeDriver
        if: ${{ env.browser == 'chrome' && env.browserstack == 'false' }}
        uses: browser-actions/setup-chrome@v2
        with:
          chrome-version: ${{ env.browserVersion }}
          install-chromedriver: true

      - name: Set up EdgeDriver
        if: ${{ env.browser == 'edge' && env.browserstack == 'false' }}
        uses: microsoft/setup-msedge-driver@v1
        with:
          edge-version: ${{ env.browserVersion }}

      - name: Run TestNG tests
        run: |
          mvn clean test -Dbrowser=${{ env.browser }} `
                         -DbrowserVersion=${{ env.browserVersion }} `
                         -Dos=${{ env.os }} `
                         -DosVersion=${{ env.osVersion }} `
                         -Dbrowserstack=${{ env.browserstack }} `
                         -DsuiteXmlFile=testng.xml
