name: Java CI - Selenium TestNG

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  repository_dispatch:   # Allows Jenkins to trigger workflow
    types: [run-selenium-tests]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Read parameters from testng.xml
        id: read_params
        shell: pwsh
        run: |
          [xml]$xml = Get-Content testng.xml
          $params = @{}
          foreach ($p in $xml.suite.parameter) {
            $params[$p.name] = $p.value
          }
          Write-Host "Parameters loaded: $params"
          echo "browserstack=$($params['browserstack'])" >> $env:GITHUB_ENV
          echo "browser=$($params['browser'])" >> $env:GITHUB_ENV
          echo "browserVersion=$($params['browserVersion'])" >> $env:GITHUB_ENV
          echo "os=$($params['os'])" >> $env:GITHUB_ENV
          echo "osVersion=$($params['osVersion'])" >> $env:GITHUB_ENV

      - name: Set up ChromeDriver
        if: ${{ env.browser == 'chrome' && env.browserstack == 'false' }}
        uses: browser-actions/setup-chrome@v2
        with:
          chrome-version: ${{ env.browserVersion }}
          install-chromedriver: true

      - name: Set up EdgeDriver
        if: ${{ env.browser == 'edge' && env.browserstack == 'false' }}
        uses: browser-actions/setup-edge@v1
        with:
          edge-version: ${{ env.browserVersion }}
          install-edgedriver: true

      - name: Run Selenium TestNG tests
        run: mvn -B clean test -DsuiteXmlFile=testng.xml \
             -Dbrowser=${{ env.browser }} \
             -Dbrowserstack=${{ env.browserstack }} \
             -DbrowserVersion=${{ env.browserVersion }} \
             -Dos=${{ env.os }} \
             -DosVersion=${{ env.osVersion }}
