name: Java CI - Browser from TestNG

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  repository_dispatch:
    types: [run-selenium-tests]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Read parameters from testng.xml
        id: get_params
        shell: pwsh
        run: |
          [xml]$xml = Get-Content testng.xml

          $browser = $xml.suite.parameter | Where-Object { $_.name -eq 'browser' } | Select-Object -ExpandProperty value
          $browserVersion = $xml.suite.parameter | Where-Object { $_.name -eq 'browserVersion' } | Select-Object -ExpandProperty value
          $os = $xml.suite.parameter | Where-Object { $_.name -eq 'os' } | Select-Object -ExpandProperty value
          $osVersion = $xml.suite.parameter | Where-Object { $_.name -eq 'osVersion' } | Select-Object -ExpandProperty value
          $browserstack = $xml.suite.parameter | Where-Object { $_.name -eq 'browserstack' } | Select-Object -ExpandProperty value

          Add-Content -Path $env:GITHUB_ENV -Value "browser=$browser"
          Add-Content -Path $env:GITHUB_ENV -Value "browserVersion=$browserVersion"
          Add-Content -Path $env:GITHUB_ENV -Value "os=$os"
          Add-Content -Path $env:GITHUB_ENV -Value "osVersion=$osVersion"
          Add-Content -Path $env:GITHUB_ENV -Value "browserstack=$browserstack"

      - name: Set up ChromeDriver
        if: ${{ env.browser == 'chrome' && env.browserstack == 'false' }}
        uses: browser-actions/setup-chrome@v2
        with:
          chrome-version: ${{ env.browserVersion }}
          install-chromedriver: true

      - name: Set up EdgeDriver
        if: ${{ env.browser == 'edge' && env.browserstack == 'false' }}
        uses: browser-actions/setup-edge@v1
        with:
          edge-version: ${{ env.browserVersion }}
          install-edgedriver: true

      - name: Run tests on ${{ env.browser }}
        shell: pwsh
        run: |
          mvn -B clean test `
<<<<<<< HEAD
            -Dbrowser=${env:browser} `
            -DbrowserVersion=${env:browserVersion} `
            -Dos=${env:os} `
            -DosVersion=${env:osVersion} `
            -Dbrowserstack=${env:browserstack} `
=======
            -Dbrowser=$env:browser `
            -DbrowserVersion=$env:browserVersion `
            -Dos=$env:os `
            -DosVersion=$env:osVersion `
            -Dbrowserstack=$env:browserstack `
>>>>>>> b2e05ba799adf2107b05f775bee6b72d33c2cf8d
            -DsuiteXmlFile="testng.xml"
