name: Java CI - Browser from TestNG

on:
  repository_dispatch:
    types: [run-selenium-tests]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # ✅ Read parameters dynamically from testng.xml
      - name: Read parameters from testng.xml
        id: get_params
        shell: pwsh
        run: |
          [xml]$xml = Get-Content testng.xml

          $params = @{ }
          foreach ($p in $xml.suite.parameter) {
            $params[$p.name] = $p.value
          }

          foreach ($key in $params.Keys) {
            Add-Content -Path $env:GITHUB_ENV -Value "$key=$($params[$key])"
          }

      # ✅ Conditional Chrome setup
      - name: Set up ChromeDriver
        if: ${{ env.browser == 'chrome' && env.browserstack == 'false' }}
        uses: browser-actions/setup-chrome@v2
        with:
          chrome-version: ${{ env.browserVersion }}
          install-chromedriver: true

      # ✅ Conditional Edge setup
      - name: Set up EdgeDriver
        if: ${{ env.browser == 'edge' && env.browserstack == 'false' }}
        uses: browser-actions/setup-edge@v1
        with:
          edge-version: ${{ env.browserVersion }}
          install-edgedriver: true

      # ✅ Run tests with all parameters
      - name: Run tests on ${{ env.browser }}
        shell: pwsh
        run: |
          mvn -B clean test `
            -Dbrowser=${{ env.browser }} `
            -DbrowserVersion=${{ env.browserVersion }} `
            -Dos=${{ env.os }} `
            -DosVersion=${{ env.osVersion }} `
            -Dbrowserstack=${{ env.browserstack }} `
            -DsuiteXmlFile="testng.xml"

      # ✅ Generate Allure report
      - name: Generate Allure Report
        if: always()
        run: mvn allure:report

      # ✅ Upload Allure report artifact
      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: target/allure-report
          path: target/site/allure-maven-plugin/
          

      # ✅ Archive TestNG reports
      - name: Archive TestNG reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: testng-reports
          path: target/surefire-reports/
