name: Java CI with Maven and Selenium

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Step 3: Set up Chrome 139
      - name: Set up Chrome
        uses: actions/setup-chrome@v1
        with:
          chrome-version: '139'

      # Step 4: Set up ChromeDriver 139
      - name: Set up ChromeDriver
        uses: webfactory/selenium-chromedriver@v1
        with:
          version: '139'

      # Step 5: Build and run tests
      - name: Build with Maven
        run: mvn -B clean test
